packages:
  - .
  - cli
  - docs

allowBuilds:
  '@atcute/time-ms': true
  '@parcel/watcher': false
  '@resvg/resvg-js': true
  'better-sqlite3': true
  'core-js': false
  'esbuild': false
  msw: true
  'sharp@0.34.5': true
  'unrs-resolver': false
  'vue-demi': false

catalogs:
  msw:
    'msw': '^2.13.2'

  storybook:
    '@storybook-vue/nuxt': 'https://pkg.pr.new/@storybook-vue/nuxt@1021'
    '@storybook/addon-a11y': '^10.3.5'
    '@storybook/addon-docs': '^10.3.5'
    '@storybook/addon-themes': '^10.3.5'
    'msw-storybook-addon': '^2.0.7'
    'storybook': '^10.3.1'
    'storybook-i18n': '^10.1.1'

  vite-plus:
    'vite': 'npm:@voidzero-dev/vite-plus-core@0.2.2'
    'vite-plus': '0.2.2'
    'vitest': '4.1.9'
    '@vitest/browser-playwright': '4.1.9'
    '@vitest/coverage-v8': '4.1.9'

dedupePeers: true

ignoreDepScripts: true

ignoreWorkspaceRootCheck: true

minimumReleaseAgeExclude:
  - vue-data-ui@3.22.6

overrides:
  '@types/node': 24.13.2
  nuxt-og-image: ^6.6.0
  sharp: 0.35.3
  vite: 'catalog:vite-plus'
  vitest: 'catalog:vite-plus'
  vue-router: 5.1.0
  markdown-exit: 1.1.0-beta.2
  oxc-parser: 0.138.0

packageExtensions:
  '@nuxt/scripts':
    dependencies:
      estree-walker: ^3.0.3

patchedDependencies:
  '@jsr/deno__doc@0.189.1': patches/@jsr__deno__doc@0.189.1.patch
  '@nuxt/test-utils': patches/@nuxt__test-utils.patch

savePrefix: ''

shellEmulator: true
