packages:
  - .
  - cli
  - docs

allowBuilds:
  '@atcute/time-ms': true
  '@parcel/watcher': false
  '@resvg/resvg-js': true
  'better-sqlite3': true
  'core-js': false
  'esbuild': false
  msw: true
  'sharp@0.34.5': true
  'unrs-resolver': false
  'vue-demi': false

catalogs:
  msw:
    'msw': '^2.13.2'

  storybook:
    '@storybook-vue/nuxt': 'https://pkg.pr.new/@storybook-vue/nuxt@1021'
    '@storybook/addon-a11y': '^10.3.5'
    '@storybook/addon-docs': '^10.3.5'
    '@storybook/addon-themes': '^10.3.5'
    'msw-storybook-addon': '^2.0.7'
    'storybook': '^10.3.1'
    'storybook-i18n': '^10.1.1'

dedupePeers: true

ignoreDepScripts: true

ignoreWorkspaceRootCheck: true

overrides:
  '@types/node': 24.12.0
  nuxt-og-image: ^6.6.0
  sharp: 0.34.5
  vite: npm:@voidzero-dev/vite-plus-core@0.1.20
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.20
  vue: 3.5.39
  vue-router: 5.0.4

packageExtensions:
  '@nuxt/scripts':
    dependencies:
      estree-walker: ^3.0.3
  'unplugin-vue-markdown':
    peerDependencies:
      'vite': '^2.0.0 || ^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0 || ^6.0.0 || ^7.0.0 ||
        ^8.0.0'

patchedDependencies:
  '@jsr/deno__doc@0.189.1': patches/@jsr__deno__doc@0.189.1.patch
  '@nuxt/test-utils': patches/@nuxt__test-utils.patch

savePrefix: ''

shellEmulator: true
