name: dependency-diff

on:
  pull_request:
    branches:
      - main
      - release
    paths:
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - docs/package.json
      - cli/package.json

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-diff:
    name: 🔎 Dependency diff
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 🔎 Compare dependencies
        id: analyze
        uses: e18e/action-dependency-diff@f825d5b5c5ce0a42dc46c47ec20de24460affcd8 # v1.5.0
        with:
          mode: artifact
          detect-replacements: 'true'
          # Too noisy. Disabling until this can report on duplicate CHANGES in this PR.
          duplicate-threshold: '999'
          dependency-threshold: '15'
          size-threshold: '200000'

      - name: 📤 Upload artifact
        if: steps.analyze.outputs.artifact-path
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: e18e-diff-result
          path: ${{ steps.analyze.outputs.artifact-path }}
